# Visit https://black.readthedocs.io/en/stable/integrations/github_actions.html for full reference

name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
          jupyter: true
          version: "~= 22.0"
