name: Latest Blog Posts

on:
  # Schedule daily updates
  schedule: [{cron: "50 2 * * *"}] # Runs at 02:50 America/New_York every day
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push: {branches: ["master", "main"]}

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        if: ${{ success() || failure() }}
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        if: ${{ success() || failure() }}
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          config_timezone: America/New_York
          feed_list: "https://dev.to/feed/pemtajo, https://medium.com/feed/@pemtajo"
          #output_action: gist
          #committer_gist: ${{ secrets.METRICS_TOKEN }}
          commits_authoring: Seth Labadie, sethlabadie, sethlabadie@gmail.com, sethlabadie@users.noreply.github.com
          output_condition: data-changed
          config_display: regular
          retries: 3
          retries_delay: 60
          retries_output_action: 3
          retries_delay_output_action: 30
