name: DailyDotDevCard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - master, main
  schedule:
    - cron: "21 0 * * *"

jobs:
  DailyDotDevCard:
    runs-on: ubuntu-latest
    steps:
      - name: DailyDotDevCard
        uses: dailydotdev/action-devcard@2.3.1
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}

