# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "17 0 * * *"}] # Runs at 00:17 America/New_York every day
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: America/New_York
          filename: metrics.plugin.github.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
