# Visit XXXXXX for full reference

name: DailyDotDevCard

on:
  # Schedule daily updates
  schedule: [{cron: "44 1 * * *"}] # Runs at 01:44 America/New_York every day
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push: {branches: ["master", "main"]}

jobs:
  DailyDotDevCard:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:

      - name: DailyDotDevCard
        if: ${{ success() || failure() }}
        uses: dailydotdev/action-devcard@3.0.0
        with:
          config_timezone: America/New_York
          filename: DailyDotDevCard.svg
          user_id: ${{ secrets.DEVCARD_ID }}
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
