# Visit XXXXXX for full reference

name: DailyDotDevCard

on:
  schedule: [{cron: "44 1 * * *"}] # Runs at 01:44 America/New_York every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  #push: {branches: ["master", "main"]} # (optional) Run workflow when pushing on master/main

jobs:
  DailyDotDevCard:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:

      - name: DailyDotDevCard
        if: ${{ success() || failure() }}
        uses: dailydotdev/action-devcard@3.2.1
        with:
          user_id: ${{ secrets.DEVCARD_ID }}
          commit_branch: devcard
          commit_filename: assets/img/devcard.png
          commit_message: "chore: update ${filename}"
