# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: GitHub Metrics - Languages

on:
  schedule: [{cron: "12 2 * * *"}] # Runs at 02:12 America/New_York every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  #push: {branches: ["master", "main"]} # (optional) Run workflow when pushing on master/main

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
      
    steps:

      - name: GitHub Metrics - Languages
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/New_York
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          #output_action: gist
          #committer_gist: ${{ secrets.METRICS_TOKEN }}
          commits_authoring: Seth Labadie, sethlabadie, sethlabadie@gmail.com, sethlabadie@users.noreply.github.com
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_other: no
          plugin_languages_ignored: html, css, scss, Jupyter Notebook, svg, png, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_skipped: fireship-io-git-sticker, js-sticker, Complete-Python-3-Bootcamp, Plotly-Dashboards-with-Dash, Python-Narrative-Journey, readme-generator, installfest, Code-Platoon-Curriculum---Oscar-Platoon, foundations_for_deep_learning, ISLR-python, lowlighter/metrics
          # plugin_languages_aliases: javascript:JS typescript:TS
          plugin_languages_colors: github
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_recent_categories: data, markup, programming, prose
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 30
          plugin_languages_threshold: 0
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 30
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          output_condition: data-changed
          config_display: regular
          retries: 3
          retries_delay: 60
          retries_output_action: 3
          retries_delay_output_action: 30
