# Visit # https://github.com/lowlighter/metrics/blob/master/source/plugins/wakatime/README.md for full reference

name: GitHub Metrics WakaTime

on:
  # Schedule daily updates
  schedule: [{cron: "32 0 * * *"}] # Runs at 00:17 America/New_York every day
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push: {branches: ["master", "main"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:
          
      - name: GitHub Metrics - WakaTime
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/New_York
          filename: metrics.plugin.wakatime.svg
          token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 10
          plugin_wakatime_languages_ignored: tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_wakatime_sections: projects, languages, editors, os
