# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: GitHub Metrics - Achievements

on:
  schedule: [{cron: "29 0 * * *"}] # Runs at 00:29 America/New_York every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  #push: {branches: ["master", "main"]} # (optional) Run workflow when pushing on master/main

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:

      - name: GitHub Metrics - Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/New_York
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          #output_action: gist
          #committer_gist: ${{ secrets.METRICS_TOKEN }}
          commits_authoring: Seth Labadie, sethlabadie, sethlabadie@gmail.com, sethlabadie@users.noreply.github.com
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_other: no
          plugin_achievements: yes
          plugin_achievements_display: compact
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          output_condition: data-changed
          config_display: regular
          retries: 3
          retries_delay: 60
          retries_output_action: 3
          retries_delay_output_action: 30
