# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: LeetCode

on:
  schedule: [{cron: "51 2 * * *"}] # Runs at 02:51 America/New_York every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  #push: {branches: ["master", "main"]} # (optional) Run workflow when pushing on master/main

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:
          
      - name: LeetCode
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/New_York
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          #output_action: gist
          #committer_gist: ${{ secrets.TOKEN }}
          commits_authoring: Seth Labadie, sethlabadie, sethlabadie@gmail.com, sethlabadie@users.noreply.github.com
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: sethlabadie
          plugin_leetcode_sections: solved, skills, recent
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          output_condition: data-changed
          config_display: regular
          retries: 3
          retries_delay: 60
          retries_output_action: 3
          retries_delay_output_action: 30
