# https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md

name: Metrics Languages Most Used (in-depth)

on:
  # Schedule daily updates
  schedule: [{cron: "28 0 * * *"}] # Runs at 00:17 America/New_York every day
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push: {branches: ["master", "main"]}
  
jobs:
  Metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write

    steps:
      
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.in-depth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_other: no
          commits_authoring: Seth Labadie, sethlabadie, sethlabadie@gmail.com
          plugin_languages_skipped: lowlighter/metrics
          plugin_languages_ignored: tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_sections: most-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_threshold: 8
          plugin_languages_limit: 10
          plugin_languages_analysis_timeout: 30
          output_condition: data-changed
          config_display: regular
          retries: 3
          retries_delay: 60
          retries_output_action: 3
          retries_delay_output_action: 30
