# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: GitHub Metrics Intruduction

on:
  # Schedule daily updates
  schedule: [{cron: "22 0 * * *"}] # Runs at 00:17 America/New_York every day
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push: {branches: ["master", "main"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:
          
      - name: GitHub Metrics - Introduction
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/New_York
          filename: metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: sethlabadie
          plugin_introduction: yes
