# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: StackOverflow

on:
  # Schedule daily updates
  schedule: [{cron: "55 2 * * *"}] # Runs at 02:55 America/New_York every day
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push: {branches: ["master", "main"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:
          
      - name: StackOverflow
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/New_York
          filename: metrics.plugin.stackoverflow.svg
          token: NOT_NEEDED
          #output_action: gist
          #committer_gist: ${{ secrets.TOKEN }}
          commits_authoring: Seth Labadie, sethlabadie, sethlabadie@gmail.com, sethlabadie@users.noreply.github.com
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 5692844
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 2 # Display limit (entries per section)
          #plugin_stackoverflow_lines: 4 # Display limit (lines per questions and answers)
          #plugin_stackoverflow_lines_snippet: 2 # Display limit (lines per code snippets)
          output_condition: data-changed
          config_display: regular
          retries: 3
          retries_delay: 60
          retries_output_action: 3
          retries_delay_output_action: 30
