# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: GitHub Metrics - Base

on:
  # Schedule daily updates
  schedule: [{cron: "17 0 * * *"}] # Runs at 00:17 America/New_York every day
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push: {branches: ["master", "main"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:
          
      - name: GitHub Metrics - Base
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/New_York
          filename: metrics.plugin.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          #output_action: gist
          #committer_gist: ${{ secrets.METRICS_TOKEN }}
          commits_authoring: Seth Labadie, sethlabadie, sethlabadie@gmail.com, sethlabadie@users.noreply.github.com
          user: sethlabadie
          plugin_introduction: yes
          #base: ""
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          base_hireable: yes
          output_condition: data-changed
          config_display: regular
          retries: 3
          retries_delay: 60
          retries_output_action: 3
          retries_delay_output_action: 30
