# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: GitHub Metrics - Sponsors

on:
  # Schedule daily updates
  schedule: [{cron: "22 1 * * *"}] # Runs at 01:22 America/New_York every day
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push: {branches: ["master", "main"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:

      - name: GitHub Metrics - Sponsors
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/New_York
          filename: metrics.plugin.sponsors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          #output_action: gist
          #committer_gist: ${{ secrets.METRICS_TOKEN }}
          commits_authoring: Seth Labadie, sethlabadie, sethlabadie@gmail.com, sethlabadie@users.noreply.github.com
          base: ""
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsorships: yes
          plugin_sponsorships_sections: amount
          output_condition: data-changed
          config_display: regular
          retries: 3
          retries_delay: 60
          retries_output_action: 3
          retries_delay_output_action: 30
