# https://github.com/lowlighter/metrics/blob/master/source/plugins/topics/README.md

name: Icons

on:
  # Schedule daily updates
  schedule: [{cron: "14 1 * * *"}] # Runs at 01:07 America/New_York every day
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  #push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 0
          plugin_topics_mode: icons
