# Visit xxx for full reference

name: Update Credly Badges

on:
  schedule: [{cron: "23 3 * * *"}] # Runs at 03:23 America/New_York every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  #push: {branches: ["master", "main"]} # (optional) Run workflow when pushing on master/main

jobs:
  update_credly_badges:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:
          
      - name: Update Credly Badges
        if: ${{ success() || failure() }}
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: seth-labadie # optional, but default will use the same from github
          #output_action: gist
          #committer_gist: ${{ secrets.METRICS_TOKEN }}

