name: Update WakaTime Stats

on:
  schedule: [{cron: "44 2 * * *"}] # Runs at 02:44 America/New_York every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  #push: {branches: ["master", "main"]} # (optional) Run workflow when pushing on master/main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      
    steps:
      - name: Update WakaTime Stats
        if: ${{ success() || failure() }}
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          #output_action: gist
          #committer_gist: ${{ secrets.METRICS_TOKEN }}
          SHOW_TIME: true
          SHOW_TITLE: true

